import {
  accoutOfficeTxt,
  aamustedCanteenPopupTxt,
  aamustedClinicPopupTxt,
  aamustedFootballPitchPopupTxt,
  aamustedMainEntrancePopupTxt,
  aamustedWorkShopPopupTxt,
  automotiveWorkshopPopupTxt,
  administrationPopUpTxt,
  AtmEcobankTxt,
  AtmGBCPouUpTxt,
  autonomyAnexPopupTxt,
  autonomyPopuptxt,
  campusSecurityPostPopupTxt,
  computerLabOnePopUpTxt,
  computerLabTwoPopUpTxt,
  constructionLabPopupTxt,
  deanFTEOfficeTxt,
  fasmePopupTxt,
  fbr10OfficeTxt,
  fbr7OfficeTxt,
  fbr9OfficeTxt,
  frankyJayPopupTxt,
  GraduateLecutureBlockPouUpTxt,
  ictLibraryBlockAnexPopupTxt,
  issahPavillionPopupTxt,
  kwamanmnaRuralBankPopupTxt,
  mechanicalWorkShopPopupTxt,
  newAuditoriumPopupTxt,
  newFocultyBuildingPopupTxt,
  newLectureBlockPopupTxt,
  newLibraryPopupTxt,
  nanaBanahenePopUpTxt,
  oldLibraryPopupTxt,
  opokuWarePopupText,
  opokuWareTenisCourtPopupTxt,
  robPopupTxt,
  srcSecretarietPopupTxt,
  stWilliamsChaplaincyPopupTxt,
  UBSAnexPopupTxt,
  ubaPopupTxt,
  uncompAuditoriumPopupTxt,
  kesewaaTxt,
  tourismAndHospitalityPopupTxt,
  facultyOfTechnicalEducationPopupTxt,
  atwimahallPopupTxt
} from "./popupText";

export const coordinatesData = [
  {
    coordinates: [6.6957, -1.6764],
    title: "Kesewaa hostel",
    buttonId: "kesewaa-btn",
    popupText: kesewaaTxt,
  },
  {
    coordinates: [6.6973, -1.68232],
    title: "ATM Ecobank",
    buttonId: "atm-ecobank-btn",
    popupText: AtmEcobankTxt,
  },
  {
    coordinates: [6.69734, -1.68232],
    title: "ATM GBC",
    buttonId: "atm-gbc-btn",
    popupText: AtmGBCPouUpTxt,
  },
  {
    coordinates: [6.69714, -1.6798],
    title: "AAMUSTED Clinic",
    buttonId: "aamusted-clinic-btn",
    popupText: aamustedClinicPopupTxt,
  },
  {
    coordinates: [6.69585, -1.67741],
    title: "AAMUSTED main entrance",
    buttonId: "main-entrance",
    popupText: aamustedMainEntrancePopupTxt,
  },
  {
    coordinates: [6.70013, -1.68063],
    title: "Tourism and hospitality Lab",
    buttonId: "hospitality-tourism-btn",
    popupText: tourismAndHospitalityPopupTxt,
  },
  {
    coordinates: [6.7001, -1.68037],
    title: "Mechanical workshop",
    buttonId: "mechenical-workshop-btn",
    popupText: mechanicalWorkShopPopupTxt,
  },
  {
    coordinates: [6.69746, -1.68041],
    title: "Nana Banahene study pavillion",
    buttonId: "nana-banahene-btn",
    popupText: nanaBanahenePopUpTxt,
  },
  {
    coordinates: [6.69804, -1.68066],
    title: "Account Office",
    buttonId: "account-office-btn",
    popupText: accoutOfficeTxt,
  },
  {
    coordinates: [6.69804, -1.68066],
    title: "Administration",
    buttonId: "administration-btn",
    popupText: administrationPopUpTxt,
  },
  {
    coordinates: [6.69804, -1.68066],
    title: "FBR 7",
    buttonId: "fbr7-btn",
    popupText: fbr7OfficeTxt,
  },
  {
    coordinates: [6.69804, -1.68066],
    title: "FBR 9",
    buttonId: "fbr9-btn",
    popupText: fbr9OfficeTxt,
  },
  {
    coordinates: [6.69804, -1.68066],
    title: "FBR 10",
    buttonId: "fbr10-btn",
    popupText: fbr10OfficeTxt,
  },
  {
    coordinates: [6.69832, -1.68006],
    title: "Faculty of Technical Education (FTE)",
    buttonId: "faculty-of-tech-edu-btn",
    popupText: facultyOfTechnicalEducationPopupTxt,
  },
  {
    coordinates: [6.69847, -1.68345],
    title: "AAMUSTED canteen",
    buttonId: "canteen-btn",
    popupText: aamustedCanteenPopupTxt,
  },
  {
    coordinates: [6.69841, -1.68094],
    title: "Uncompleted auditorium",
    buttonId: "uncom-auditorium-btn",
    popupText: uncompAuditoriumPopupTxt,
  },
  {
    coordinates: [6.69727, -1.68368],
    title: "SRC secretariet",
    buttonId: "src-secretariet",
    popupText: srcSecretarietPopupTxt,
  },
  {
    coordinates: [6.69721, -1.68372],
    title: "Kwamanman rural bank",
    buttonId: "kwamanman-rural-bank",
    popupText: kwamanmnaRuralBankPopupTxt,
  },
  {
    coordinates: [6.70169, -1.68267],
    title: "Issah pavillion",
    buttonId: "issah-pavillion-btn",
    popupText: issahPavillionPopupTxt,
  },
  {
    coordinates: [6.69793, -1.67995],
    title: "New auditorium",
    buttonId: "new-auditorium-btn",
    popupText: newAuditoriumPopupTxt,
  },
  {
    coordinates: [6.69797, -1.68185],
    title: "New library",
    buttonId: "new-library-btn",
    popupText: newLibraryPopupTxt,
  },
  {
    coordinates: [6.69792, -1.68169],
    title: "Old library",
    buttonId: "old-library",
    popupText: oldLibraryPopupTxt,
  },
  {
    coordinates: [6.70025, -1.68137],
    title: "ICT & Library Block",
    buttonId: "ict-library-btn",
    popupText: ictLibraryBlockAnexPopupTxt,
  },
  {
    coordinates: [6.69676, -1.6822],
    title: "Campus security post",
    buttonId: "capus-security-post-btn",
    popupText: campusSecurityPostPopupTxt,
  },
  {
    coordinates: [6.6957, -1.6764],
    title: "Kesewaa hostel",
    buttonId: "kesewaa-btn",
    popupText: kesewaaTxt,
  },
  {
    coordinates: [6.69779, -1.68397],
    title: "Opoku ware mosque",
    buttonId: "opoku-ware-mosqueBtn",
    popupText: "Opoku ware mosque",
  },
  {
    coordinates: [6.69755, -1.68333],
    title: "Opoku Ware tenis court",
    buttonId: "opoku-ware-tenis-btn",
    popupText: opokuWareTenisCourtPopupTxt,
  },
  {
    coordinates: [6.69782, -1.68286],
    title: "Opoku ware hall",
    buttonId: "opoku-ware-btn",
    popupText: opokuWarePopupText,
  },
  {
    coordinates: [6.70181, -1.67666],
    title: "St Williams Chaplaincy",
    buttonId: "st-wiliams-btn",
    popupText: stWilliamsChaplaincyPopupTxt,
  },
  {
    coordinates: [6.70131, -1.6767],
    title: "Autonomy hall anex",
    buttonId: "autonomy-anex-btn",
    popupText: autonomyAnexPopupTxt,
  },
  {
    coordinates: [6.69659, -1.67957],
    title: "Atwima hall",
    buttonId: "atwima-hall-btn",
    popupText: atwimahallPopupTxt,
  },
  {
    coordinates: [6.6957, -1.6764],
    title: "Kesewaa hostel",
    buttonId: "kesewaa-btn",
    popupText: kesewaaTxt,
  },
  {
    coordinates: [6.70002, -1.67947],
    title: "Automotive workshop",
    buttonId: "automotive-workshop",
    popupText: automotiveWorkshopPopupTxt,
  },
  {
    coordinates: [6.69736, -1.68338],
    title: "UBA",
    buttonId: "uba",
    popupText: ubaPopupTxt,
  },
  {
    coordinates: [6.70111, -1.68312],
    title: "NFB",
    buttonId: "NFB-btn",
    popupText: newFocultyBuildingPopupTxt,
  },
  {
    coordinates: [6.70119, -1.68301],
    title: "NLB",
    buttonId: "NLB-btn",
    popupText: newLectureBlockPopupTxt,
  },
  {
    coordinates: [6.69777, -1.68092],
    title: "Computer lab one",
    buttonId: "computer-lab-one-btn",
    popupText: computerLabOnePopUpTxt,
  },
  {
    coordinates: [6.69777, -1.68092],
    title: "Computer lab two",
    buttonId: "computer-lab2-btn",
    popupText: computerLabTwoPopUpTxt,
  },
  {
    coordinates: [6.69678, -1.67712],
    title: "University Basic School (UBS)",
    buttonId: "ubs-btn",
    popupText: UBSAnexPopupTxt,
  },
  {
    coordinates: [6.70058, -1.67685],
    title: "Autonomy hall",
    buttonId: "autonomy-hall-btn",
    popupText: autonomyPopuptxt,
  },
  {
    coordinates: [6.70025, -1.68137],
    title: "ICT & Library Block",
    buttonId: "ict-library-btn",
    popupText: ictLibraryBlockAnexPopupTxt,
  },
  {
    coordinates: [6.70181, -1.67666],
    title: "St Williams Chaplaincy",
    buttonId: "st-wiliams-btn",
    popupText: stWilliamsChaplaincyPopupTxt,
  },
];
